name: 验证GitHub Token
    run: |
      echo "正在验证GitHub Token..."
      response=$(curl -s -o /dev/null -w "%{http_code}" \
        -H "Authorization: Bearer ${{ secrets.PUSH_TOKEN }}" \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        "https://api.github.com/gists/${{ secrets.GIST_ID }}")

      if [ "$response" -eq 200 ]; then
        echo "✅ Token验证成功"
      else
        echo "❌ Token验证失败，HTTP状态码: $response"
        exit 1
      fi
